// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Udemy_clone.Data;

#nullable disable

namespace Udemy_clone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230814105215_initandseed")]
    partial class initandseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Udemy_clone.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            Description = "Video 1 Description",
                            Duration = 100,
                            Thumbnail = "https://via.placeholder.com/150",
                            Title = "Video 1",
                            VideoUrl = "https://www.youtube.com/embed/1"
                        },
                        new
                        {
                            VideoId = 2,
                            Description = "Video 2 Description",
                            Duration = 200,
                            Thumbnail = "https://via.placeholder.com/150",
                            Title = "Video 2",
                            VideoUrl = "https://www.youtube.com/embed/2"
                        },
                        new
                        {
                            VideoId = 3,
                            Description = "Video 3 Description",
                            Duration = 300,
                            Thumbnail = "https://via.placeholder.com/150",
                            Title = "Video 3",
                            VideoUrl = "https://www.youtube.com/embed/3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
